//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : CvModel
//  @ File Name : ConvexHullGenerator.cs
//  @ Date : 13/04/2013
//  @ Author : 
//
//


public class ConvexHullGenerator : ModelDataGenerator, ModelDataGenerator2D
{
	public void ConvexHullGenerator()
	{
	}
}
