//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : CvModel
//  @ File Name : DirectProjectionGenerator.cs
//  @ Date : 13/04/2013
//  @ Author : 
//
//


public class DirectProjectionGenerator : ModelDataGenerator, ModelDataGenerator2D
{
	public void DirectProjectionGenerator()
	{
	}
}
