//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : CvModel
//  @ File Name : EquiSphericalViewProvider.cs
//  @ Date : 13/04/2013
//  @ Author : 
//
//


public class EquiSphericalViewProvider : ModelViewProvider, ModelViewProvider
{
	public void EquiSphericalViewProvider(double radius, int nbPoints)
	{
	}
}
