//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : CvModel
//  @ File Name : ModelDataGeneratorFactory.cs
//  @ Date : 13/04/2013
//  @ Author : 
//
//


public class ModelDataGeneratorFactory : XmlFactory
{
	public ModelDataGenerator CreateConvexHullGenerator()
	{
	}
	public ModelDataGenerator CreateDirectProjectionGenerator()
	{
	}
}
