//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : CvModel
//  @ File Name : ModelDataGenerator.cs
//  @ Date : 13/04/2013
//  @ Author : 
//
//


public class ModelDataGenerator 
{
	public ModelData GenerateData()
	{
	}
}
