//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : CvModel
//  @ File Name : ModelViewProvider.cs
//  @ Date : 13/04/2013
//  @ Author : 
//
//


public abstract class ModelViewProvider 
{
	public Vector3[] ProvideViews()
	{
	}
}
