//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : CvModel
//  @ File Name : ModelViewProviderFactory.cs
//  @ Date : 13/04/2013
//  @ Author : 
//
//


public class ModelViewProviderFactory : XmlFactory
{
	public ModelViewProvider CreateEquiSphericalViewProvider()
	{
	}
}
