//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : CvModel
//  @ File Name : ModelDataGenerator2D.cs
//  @ Date : 13/04/2013
//  @ Author : 
//
//


public abstract class ModelDataGenerator2D : ModelDataGenerator
{
	private ModelViewProvider viewProvider;
	public void GenerateDataFromView(Vector3 view)
	{
	}
}
