//
//
//  Generated by StarUML(tm) C# Add-In
//
//  @ Project : CvModel
//  @ File Name : XmlFactory.cs
//  @ Date : 13/04/2013
//  @ Author : 
//
//


public class XmlFactory 
{
	public T CreateFromXml(string xmlPath)
	{
	}
}
